### ISSUE TITLE
执行excel报错

### ISSUE THREAD

**Issue by zxcv5733** [WenchaoZeng/SqlDataProcessor#11]
[42122-220]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:514)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.expression.ExpressionColumn.getColumnException(ExpressionColumn.java:244)
	at org.h2.expression.ExpressionColumn.optimizeOther(ExpressionColumn.java:226)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:213)
	at org.h2.command.query.Select.prepareExpressions(Select.java:1170)
	at org.h2.command.query.Query.prepare(Query.java:218)
	at org.h2.command.Parser.prepareCommand(Parser.java:583)
	at org.h2.engine.SessionLocal.prepareLocal(SessionLocal.java:634)
	at org.h2.engine.SessionLocal.prepareCommand(SessionLocal.java:557)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1116)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:237)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:223)
	at com.zwc.sqldataprocessor.SqlExecutor.execRawSql(SqlExecutor.java:39)
	... 4 more

**Comment by WenchaoZeng** [comment]
> 只能在mac上执行，windows、linux上都不行啊

你是在windows下的么? 这个错误, 你可以发完整一点么? 然后你的sql也发一下?

**Comment by WenchaoZeng** [comment]
有可能是你写的sql有格式错误, 比如我特意写了一个有错的sql. 错误是显示成这样. 你贴的那个错误信息, 应该也有全一点的, 会描述出来具体的错误的.
 
<img width="981" alt="image" src="https://github.com/WenchaoZeng/SqlDataProcessor/assets/1182736/b73089e2-c419-4d81-a90f-af09c27b7f00">

你看看?

**Comment by WenchaoZeng** [comment]
windows下执行的话, 之前我没提供bat批处理文件, 所以需要在bash环境(比如gitbash)里启动. 现在我在最新版里也提供了一个start.bat文件了, 就可以在命令行里直接启动了.

**Comment by zxcv5733** [comment]
![image](https://github.com/WenchaoZeng/SqlDataProcessor/assets/46121339/9da0a89f-3d42-4857-b11e-129a5c49af0b)
sql文件

**Comment by zxcv5733** [comment]
![image](https://github.com/WenchaoZeng/SqlDataProcessor/assets/46121339/e136e028-d583-48ac-83e4-e8b27f047684)
执行的sql报错

**Comment by zxcv5733** [comment]
excel的文件内容不能发给你

**Comment by zxcv5733** [comment]
![image](https://github.com/WenchaoZeng/SqlDataProcessor/assets/46121339/da58f626-6e10-460b-9a9a-42a95a7acfff)
说这个字段是重复的

**Comment by zxcv5733** [comment]
![image](https://github.com/WenchaoZeng/SqlDataProcessor/assets/46121339/99616529-3417-4ea0-85c6-8ac47ad99cb1)

**Comment by WenchaoZeng** [comment]
感谢, 的确是不能出现重复的列的, 需要把sheet里面重复的列删掉.

**Comment by zxcv5733** [comment]
1

**Comment by WenchaoZeng** [comment]
> 控制台数据太多，我把控制台日志打印指定文件夹才看到

了解了, 我看一下怎么优化这个问题, 这个问题应该是只有h2数据才会有, 之前我在mysql也遇到过sql报错, 但是不会把完整的sql打印出出来. 应该是h2这边把完整的sql打印出来了.

**Comment by WenchaoZeng** [comment]
我已经发布了一个新的版本(版本: 2023-08-17)了, 这个h2数据库SQL错误输出太多的问题已经解决了, 现在可以很容易就看到具体的错误了.

<img width="629" alt="image" src="https://github.com/WenchaoZeng/SqlDataProcessor/assets/1182736/f7442bc1-97fc-4aed-a8b4-87fdf5f67ad1">
